#!/bin/bash

./make

for i in `seq 0 99`;
do
    rm -f results/storeresults$i.txt
done

for i in `seq 0 $(($2 - 1))`;
do
    cp submission.jar   results/$i/
done

for i in `seq 0 $(($2 - 1))`;
do
    open -a Terminal.app results/$i/run$1$i
done
